exclude: 'migrations'
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        args: [--skip-string-normalization, --line-length=100]
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.2
    hooks:
      - id: autoflake
        args: [--recursive, --in-place, --remove-unused-variables, --remove-all-unused-imports]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
